export const defaultThemes = [
 {
      default: true,
      name: 'Hyaena',
      colors: [
      { label: 'text light highlight', tag: '--color-text-light-highlight', value: '#f0f0e0' },
      { label: 'text light heading', tag: '--color-text-light-heading', value: '#c9c7b8' },
      { label: 'text light primary', tag: '--color-text-light-primary', value: '#b5b3a4' },
      { label: 'text dark primary', tag: '--color-text-dark-primary', value: '#191813' },
      { label: 'text dark secondary', tag: '--color-text-dark-secondary', value: '#4b4a44' },
      { label: 'text dark header', tag: '--color-text-dark-header', value: '#23221d' },
      { label: 'text dark inactive', tag: '--color-text-dark-inactive', value: '#7a7971' },
      { label: 'text hyperlink', tag: '--color-text-hyperlink', value: '#cf337b' },
      { label: 'text light 0', tag: '--color-text-light-0', value: '#ffffff' },
      { label: 'text light 1', tag: '--color-text-light-1', value: '#eeeeee' },
      { label: 'text light 2', tag: '--color-text-light-2', value: '#dddddd' },
      { label: 'text light 3', tag: '--color-text-light-3', value: '#cccccc' },
      { label: 'text light 4', tag: '--color-text-light-4', value: '#bbbbbb' },
      { label: 'text light 5', tag: '--color-text-light-5', value: '#aaaaaa' },
      { label: 'text light 6', tag: '--color-text-light-6', value: '#999999' },
      { label: 'text light 7', tag: '--color-text-light-7', value: '#888888' },
      { label: 'text dark 1', tag: '--color-text-dark-1', value: '#111111' },
      { label: 'text dark 2', tag: '--color-text-dark-2', value: '#222222' },
      { label: 'text dark 3', tag: '--color-text-dark-3', value: '#444444' },
      { label: 'text dark 4', tag: '--color-text-dark-4', value: '#555555' },
      { label: 'text dark 5', tag: '--color-text-dark-5', value: '#666666' },
      { label: 'text dark 6', tag: '--color-text-dark-6', value: '#777777' },
      { label: 'border light 1', tag: '--color-border-light-1', value: '#dddddd' },
      { label: 'border light 2', tag: '--color-border-light-2', value: '#999999' },
      { label: 'border dark 1', tag: '--color-border-dark-1', value: '#111111' },
      { label: 'border dark 2', tag: '--color-border-dark-2', value: '#222222' },
      { label: 'border dark 3', tag: '--color-border-dark-3', value: '#333333' },
      { label: 'border dark 4', tag: '--color-border-dark-4', value: '#444444' },
      { label: 'border dark 5', tag: '--color-border-dark-5', value: '#666666' },
      { label: 'shadow primary', tag: '--color-shadow-primary', value: '#fa1eb8' },
      { label: 'shadow highlight', tag: '--color-shadow-highlight', value: '#cf337b' },
      { label: 'shadow dark', tag: '--color-shadow-dark', value: '#000000' },
      { label: 'underline inactive', tag: '--color-underline-inactive', value: '#7a7971' },
      { label: 'underline active', tag: '--color-underline-active', value: '#372764' },
      { label: 'underline header', tag: '--color-underline-header', value: '#6b2780' },
      { label: 'border light highlight', tag: '--color-border-light-highlight', value: '#d20074' },
      { label: 'border light primary', tag: '--color-border-light-primary', value: '#b5b3a4' },
      { label: 'border light secondary', tag: '--color-border-light-secondary', value: '#c9c7b8' },
      { label: 'border light tertiary', tag: '--color-border-light-tertiary', value: '#7a7971' },
      { label: 'border dark', tag: '--color-border-dark', value: '#000000' },
      { label: 'border dark primary', tag: '--color-border-dark-primary', value: '#191813' },
      { label: 'border dark secondary', tag: '--color-border-dark-secondary', value: '#23221d' },
      { label: 'border dark tertiary', tag: '--color-border-dark-tertiary', value: '#4b4a44' },
      { label: 'border highlight', tag: '--color-border-highlight', value: '#cf337b' },
      { label: 'border highlight alt', tag: '--color-border-highlight-alt', value: '#fa1eb8' },
      { label: 'bg btn minor inactive', tag: '--color-bg-btn-minor-inactive', value: '#c9c7b8' },
      { label: 'bg btn minor active', tag: '--color-bg-btn-minor-active', value: '#d20074' },
      { label: 'bg option', tag: '--color-bg-option', value: '#dad8cc' },
      { label: 'scrollbar color', tag: 'scrollbar-color', value: '#6b2780'},
      
    ],
    special: [
      { label: 'header color', tag: '--color-header-color', value: 'rgba(55, 0, 55, 0.5)'},
      { label: 'sidebar color', tag: '--sidebar-color', value: 'rgba(46, 0, 51, 0.719)' }
    ]
  },
 {
      name: 'FVTT Default',
      colors: [
      { label: 'text light highlight', tag: '--color-text-light-highlight', value: '#f0f0e0' },
      { label: 'text light heading', tag: '--color-text-light-heading', value: '#c9c7b8' },
      { label: 'text light primary', tag: '--color-text-light-primary', value: '#b5b3a4' },
      { label: 'text dark primary', tag: '--color-text-dark-primary', value: '#191813' },
      { label: 'text dark secondary', tag: '--color-text-dark-secondary', value: '#4b4a44' },
      { label: 'text dark header', tag: '--color-text-dark-header', value: '#23221d' },
      { label: 'text dark inactive', tag: '--color-text-dark-inactive', value: '#7a7971' },
      { label: 'text hyperlink', tag: '--color-text-hyperlink', value: '#ff6400' },
      { label: 'text light 0', tag: '--color-text-light-0', value: '#ffffff' },
      { label: 'text light 1', tag: '--color-text-light-1', value: '#eeeeee' },
      { label: 'text light 2', tag: '--color-text-light-2', value: '#dddddd' },
      { label: 'text light 3', tag: '--color-text-light-3', value: '#cccccc' },
      { label: 'text light 4', tag: '--color-text-light-4', value: '#bbbbbb' },
      { label: 'text light 5', tag: '--color-text-light-5', value: '#aaaaaa' },
      { label: 'text light 6', tag: '--color-text-light-6', value: '#999999' },
      { label: 'text light 7', tag: '--color-text-light-7', value: '#888888' },
      { label: 'text dark 1', tag: '--color-text-dark-1', value: '#111111' },
      { label: 'text dark 2', tag: '--color-text-dark-2', value: '#222222' },
      { label: 'text dark 3', tag: '--color-text-dark-3', value: '#444444' },
      { label: 'text dark 4', tag: '--color-text-dark-4', value: '#555555' },
      { label: 'text dark 5', tag: '--color-text-dark-5', value: '#666666' },
      { label: 'text dark 6', tag: '--color-text-dark-6', value: '#777777' },
      { label: 'border light 1', tag: '--color-border-light-1', value: '#dddddd' },
      { label: 'border light 2', tag: '--color-border-light-2', value: '#999999' },
      { label: 'border dark 1', tag: '--color-border-dark-1', value: '#111111' },
      { label: 'border dark 2', tag: '--color-border-dark-2', value: '#222222' },
      { label: 'border dark 3', tag: '--color-border-dark-3', value: '#333333' },
      { label: 'border dark 4', tag: '--color-border-dark-4', value: '#444444' },
      { label: 'border dark 5', tag: '--color-border-dark-5', value: '#666666' },
      { label: 'shadow primary', tag: '--color-shadow-primary', value: '#ff0000' },
      { label: 'shadow highlight', tag: '--color-shadow-highlight', value: '#ff6400' },
      { label: 'shadow dark', tag: '--color-shadow-dark', value: '#000000' },
      { label: 'underline inactive', tag: '--color-underline-inactive', value: '#7a7971' },
      { label: 'underline active', tag: '--color-underline-active', value: '#44191A' },
      { label: 'underline header', tag: '--color-underline-header', value: '#782e22' },
      { label: 'border light highlight', tag: '--color-border-light-highlight', value: '#f0f0e0' },
      { label: 'border light primary', tag: '--color-border-light-primary', value: '#b5b3a4' },
      { label: 'border light secondary', tag: '--color-border-light-secondary', value: '#c9c7b8' },
      { label: 'border light tertiary', tag: '--color-border-light-tertiary', value: '#7a7971' },
      { label: 'border dark', tag: '--color-border-dark', value: '#000000' },
      { label: 'border dark primary', tag: '--color-border-dark-primary', value: '#191813' },
      { label: 'border dark secondary', tag: '--color-border-dark-secondary', value: '#23221d' },
      { label: 'border dark tertiary', tag: '--color-border-dark-tertiary', value: '#4b4a44' },
      { label: 'border highlight', tag: '--color-border-highlight', value: '#ff6400' },
      { label: 'border highlight alt', tag: '--color-border-highlight-alt', value: '#ff0000' },
      { label: 'bg btn minor inactive', tag: '--color-bg-btn-minor-inactive', value: '#c9c7b8' },
      { label: 'bg btn minor active', tag: '--color-bg-btn-minor-active', value: '#b5b3a4' },
      { label: 'bg option', tag: '--color-bg-option', value: '#dad8cc' },
      { label: 'scrollbar color', tag: 'scrollbar-color', value: '#782e22' },
      
    ],
    special: [
      { label: 'header color', tag: '--color-header-color', value: ''},
      { label: 'sidebar color', tag: '--sidebar-color', value: '' }
    ]
  }
];
